### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by markmacgillivray** [JiscPER/jper-sword-out#1]
Octopus appears to fail because flask has no login manager after clean install to a virtualenv. Can you check and see which versions you have it set to install and whether a clean install works for you?

**Comment by richard-jones** [comment]
Huh, weird - there isn't a login manager required for this app, iirc.  I'll check it today.

**Comment by markmacgillivray** [comment]
yeah i did not expect it would need one, perhaps it could be something to
do with the version of octopus expecting it.

**Comment by richard-jones** [comment]
This is because the startup docs were out of date.  This app does not have a web interface, so can't be started that way.  Web startup script removed, and documentation updated.
